apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  labels:
    name: website
spec:
  ingressClassName: nginx
  rules:
  - host: website.test
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website
            port: 
              number: 80
